import { useMemo } from 'react'

// Relationship Insights — shows real, computed stats about a
// conversation: message activity, when you usually talk, reply rate,
// and average response time. Everything here is derived directly
// from the `messages` array already loaded for the open conversation
// — nothing is guessed or generated by AI, so the numbers are
// trustworthy rather than "vibes."
//
// Caveat worth keeping in mind: `messages` is whatever's currently
// loaded in the chat (your useChat hook's window), not full history,
// so on a very old/long conversation this reflects "recent activity"
// rather than all-time stats. That's fine for a "this week" framing
// but don't market it as lifetime data unless useChat loads everything.

const DAY_NAMES = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']

function computeInsights(messages, currentUserId) {
  const textMsgs = messages.filter(m => m.message_type !== 'curry' && !m.content?.startsWith('call_log:') && !m.content?.startsWith('missed_call:'))
  if (textMsgs.length === 0) return null

  // Activity by day-of-week
  const dayCounts = new Array(7).fill(0)
  const hourCounts = new Array(24).fill(0)
  textMsgs.forEach(m => {
    const d = new Date(m.created_at)
    dayCounts[d.getDay()]++
    hourCounts[d.getHours()]++
  })
  const mostActiveDayIdx = dayCounts.indexOf(Math.max(...dayCounts))
  const mostActiveDay = DAY_NAMES[mostActiveDayIdx]

  // "Usually chat at night" style label from the hour distribution
  const bucket = (h) => h < 6 ? 'late night' : h < 12 ? 'morning' : h < 17 ? 'afternoon' : h < 21 ? 'evening' : 'night'
  const bucketCounts = {}
  hourCounts.forEach((count, h) => { const b = bucket(h); bucketCounts[b] = (bucketCounts[b] || 0) + count })
  const topBucket = Object.entries(bucketCounts).sort((a, b) => b[1] - a[1])[0]?.[0] || 'day'

  // Reply rate: of all messages from the OTHER person, what fraction
  // were eventually followed by a message from ME later in the thread
  // (not necessarily the very next message, to allow for them
  // double-texting before I reply).
  let theirMsgCount = 0
  let repliedCount = 0
  const responseTimes = [] // ms between their message and my next reply

  for (let i = 0; i < textMsgs.length; i++) {
    const m = textMsgs[i]
    if (m.sender_id === currentUserId) continue
    theirMsgCount++
    // find the next message from ME after this one
    for (let j = i + 1; j < textMsgs.length; j++) {
      if (textMsgs[j].sender_id === currentUserId) {
        repliedCount++
        responseTimes.push(new Date(textMsgs[j].created_at) - new Date(m.created_at))
        break
      }
    }
  }

  const replyRate = theirMsgCount > 0 ? Math.round((repliedCount / theirMsgCount) * 100) : null
  const avgResponseMs = responseTimes.length > 0 ? responseTimes.reduce((a, b) => a + b, 0) / responseTimes.length : null

  const formatDuration = (ms) => {
    const mins = Math.round(ms / 60000)
    if (mins < 1) return '< 1 min'
    if (mins < 60) return `${mins} min${mins === 1 ? '' : 's'}`
    const hrs = Math.round(mins / 60)
    if (hrs < 24) return `${hrs} hr${hrs === 1 ? '' : 's'}`
    return `${Math.round(hrs / 24)} day${Math.round(hrs / 24) === 1 ? '' : 's'}`
  }

  return {
    totalMessages: textMsgs.length,
    mostActiveDay,
    topBucket,
    replyRate,
    avgResponseLabel: avgResponseMs !== null ? formatDuration(avgResponseMs) : null,
    sampleSize: textMsgs.length,
  }
}

export default function RelationshipInsights({ messages, currentUserId, contactName, onClose }) {
  const insights = useMemo(() => computeInsights(messages, currentUserId), [messages, currentUserId])

  if (!insights) {
    return (
      <div style={s.panel}>
        <div style={s.header}>
          <span style={s.title}>📊 Relationship Insights</span>
          <button style={s.closeBtn} onClick={onClose}>✕</button>
        </div>
        <div style={s.empty}>Not enough messages yet to show insights.</div>
      </div>
    )
  }

  return (
    <div style={s.panel}>
      <div style={s.header}>
        <span style={s.title}>📊 Insights with {contactName}</span>
        <button style={s.closeBtn} onClick={onClose}>✕</button>
      </div>

      <div style={s.grid}>
        <div style={s.card}>
          <div style={s.cardLabel}>Most active</div>
          <div style={s.cardValue}>{insights.mostActiveDay}s</div>
        </div>
        <div style={s.card}>
          <div style={s.cardLabel}>Usually chat in the</div>
          <div style={s.cardValue}>{insights.topBucket}</div>
        </div>
        {insights.replyRate !== null && (
          <div style={s.card}>
            <div style={s.cardLabel}>Reply rate</div>
            <div style={s.cardValue}>{insights.replyRate}%</div>
          </div>
        )}
        {insights.avgResponseLabel && (
          <div style={s.card}>
            <div style={s.cardLabel}>Avg. response</div>
            <div style={s.cardValue}>{insights.avgResponseLabel}</div>
          </div>
        )}
      </div>

      <div style={s.footnote}>
        Based on the last {insights.sampleSize} messages in this chat.
      </div>
    </div>
  )
}

const s = {
  panel: {
    background: 'rgba(30,30,46,0.98)', borderTop: '1px solid rgba(102,126,234,0.3)',
    padding: '14px 16px', display: 'flex', flexDirection: 'column', gap: 12,
  },
  header: { display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  title: { fontSize: 13, fontWeight: 700, color: '#fff' },
  closeBtn: { background: 'none', border: 'none', color: '#666', fontSize: 13, cursor: 'pointer' },
  empty: { fontSize: 13, color: '#9ca3af', padding: '8px 0' },
  grid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 },
  card: {
    background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.08)',
    borderRadius: 12, padding: '10px 12px',
  },
  cardLabel: { fontSize: 11, color: '#9ca3af', fontWeight: 600, marginBottom: 3 },
  cardValue: { fontSize: 17, color: '#c4b5fd', fontWeight: 700, textTransform: 'capitalize' },
  footnote: { fontSize: 10.5, color: 'rgba(255,255,255,0.3)', textAlign: 'center' },
}
