import { useState, useEffect, useMemo, useCallback } from 'react'
import { supabase } from '../lib/supabase'
import { callCurryAI } from './CurryAI'

// Relationship Insights — shows real, computed stats about a
// conversation: message activity, when you usually talk, reply rate,
// average response time, and a headline "Conversation Score" derived
// from those same numbers. Everything here is derived directly from
// the `messages` array already loaded for the open conversation —
// nothing is guessed or generated by AI, so the numbers are
// trustworthy rather than "vibes."
//
// Caveat worth keeping in mind: `messages` is whatever's currently
// loaded in the chat (your useChat hook's window), not full history,
// so on a very old/long conversation this reflects "recent activity"
// rather than all-time stats. That's fine for a "this week" framing
// but don't market it as lifetime data unless useChat loads everything.
//
// Phase 3 adds a third "Mood" tab — this ONE is AI-derived (unlike
// Score/Timeline), pulled live from recent messages in this specific
// conversation each time it's opened/refreshed, not cached or guessed
// up front.
//
// Phase 4 adds a fourth "Profile" tab — Personality Profiles. Mostly
// deterministic (active hour, message length, voice-note usage all
// come straight from timestamps/message_type), with a small AI-read
// layer on top for topics/traits, same live-per-open pattern as Mood.

const DAY_NAMES = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']

const MOOD_EMOJI = {
  positive: '😊', excited: '🤩', neutral: '🙂',
  stressed: '😮\u200d💨', anxious: '😟', sad: '😔', negative: '😕',
}

// Score is a deterministic weighted blend of three real signals —
// no AI, no vibes. Weights: reply rate matters most, response speed
// second, message volume (a proxy for "how much you actually talk")
// a distant third.
function speedScore(avgResponseMs) {
  if (avgResponseMs === null) return 50 // unknown — neutral, not penalized
  const mins = avgResponseMs / 60000
  if (mins < 5) return 100
  if (mins < 30) return 80
  if (mins < 120) return 60
  if (mins < 1440) return 40
  return 20
}

function volumeScore(totalMessages) {
  return Math.min(100, Math.round((totalMessages / 200) * 100))
}

function computeScore(replyRate, avgResponseMs, totalMessages) {
  const reply = replyRate ?? 50
  const speed = speedScore(avgResponseMs)
  const volume = volumeScore(totalMessages)
  return Math.round(reply * 0.5 + speed * 0.35 + volume * 0.15)
}

function scoreLabel(score) {
  if (score >= 85) return { emoji: '💜', label: 'Best Friend' }
  if (score >= 65) return { emoji: '🙂', label: 'Good Friend' }
  if (score >= 45) return { emoji: '👋', label: 'Regular Contact' }
  return { emoji: '🌱', label: 'New Connection' }
}

function computeInsights(messages, currentUserId) {
  const textMsgs = messages.filter(m => m.message_type !== 'curry' && !m.content?.startsWith('call_log:') && !m.content?.startsWith('missed_call:'))
  if (textMsgs.length === 0) return null

  // Activity by day-of-week
  const dayCounts = new Array(7).fill(0)
  const hourCounts = new Array(24).fill(0)
  textMsgs.forEach(m => {
    const d = new Date(m.created_at)
    dayCounts[d.getDay()]++
    hourCounts[d.getHours()]++
  })
  const mostActiveDayIdx = dayCounts.indexOf(Math.max(...dayCounts))
  const mostActiveDay = DAY_NAMES[mostActiveDayIdx]

  // "Usually chat at night" style label from the hour distribution
  const bucket = (h) => h < 6 ? 'late night' : h < 12 ? 'morning' : h < 17 ? 'afternoon' : h < 21 ? 'evening' : 'night'
  const bucketCounts = {}
  hourCounts.forEach((count, h) => { const b = bucket(h); bucketCounts[b] = (bucketCounts[b] || 0) + count })
  const topBucket = Object.entries(bucketCounts).sort((a, b) => b[1] - a[1])[0]?.[0] || 'day'

  // Reply rate: of all messages from the OTHER person, what fraction
  // were eventually followed by a message from ME later in the thread
  // (not necessarily the very next message, to allow for them
  // double-texting before I reply).
  let theirMsgCount = 0
  let repliedCount = 0
  const responseTimes = [] // ms between their message and my next reply

  for (let i = 0; i < textMsgs.length; i++) {
    const m = textMsgs[i]
    if (m.sender_id === currentUserId) continue
    theirMsgCount++
    // find the next message from ME after this one
    for (let j = i + 1; j < textMsgs.length; j++) {
      if (textMsgs[j].sender_id === currentUserId) {
        repliedCount++
        responseTimes.push(new Date(textMsgs[j].created_at) - new Date(m.created_at))
        break
      }
    }
  }

  const replyRate = theirMsgCount > 0 ? Math.round((repliedCount / theirMsgCount) * 100) : null
  const avgResponseMs = responseTimes.length > 0 ? responseTimes.reduce((a, b) => a + b, 0) / responseTimes.length : null

  const formatDuration = (ms) => {
    const mins = Math.round(ms / 60000)
    if (mins < 1) return '< 1 min'
    if (mins < 60) return `${mins} min${mins === 1 ? '' : 's'}`
    const hrs = Math.round(mins / 60)
    if (hrs < 24) return `${hrs} hr${hrs === 1 ? '' : 's'}`
    return `${Math.round(hrs / 24)} day${Math.round(hrs / 24) === 1 ? '' : 's'}`
  }

  const score = computeScore(replyRate, avgResponseMs, textMsgs.length)
  const { emoji: scoreEmoji, label: scoreLabelText } = scoreLabel(score)
  const stars = Math.max(1, Math.round(score / 20))

  return {
    totalMessages: textMsgs.length,
    mostActiveDay,
    topBucket,
    replyRate,
    avgResponseLabel: avgResponseMs !== null ? formatDuration(avgResponseMs) : null,
    sampleSize: textMsgs.length,
    score,
    scoreEmoji,
    scoreLabelText,
    stars,
  }
}

// Turns a Gemini-authored freeform object (arbitrary keys, since the
// model chooses its own field names each time it updates chat memory)
// into a readable list — "current_group_need" -> "Current group need" —
// rather than assuming any fixed schema.
function prettifyKey(key) {
  return key.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase())
}
function renderValue(v) {
  if (Array.isArray(v)) {
    return v.map(item => (typeof item === 'object' ? Object.values(item).join(' — ') : String(item))).join(', ')
  }
  if (typeof v === 'object' && v !== null) return Object.values(v).join(', ')
  return String(v)
}

function formatCallDuration(sec) {
  if (!sec) return null
  const m = Math.floor(sec / 60)
  const s2 = sec % 60
  return m > 0 ? `${m}m ${s2}s` : `${s2}s`
}

function useTimelineData(conversationId) {
  const [data, setData] = useState(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    if (!conversationId) return
    let cancelled = false
    setLoading(true)

    async function load() {
      const [firstMsgRes, longestCallRes, curryMemRes] = await Promise.all([
        supabase.from('messages').select('created_at').eq('conversation_id', conversationId)
          .order('created_at', { ascending: true }).limit(1).maybeSingle(),
        supabase.from('active_calls').select('duration_seconds, call_type, created_at')
          .eq('conversation_id', conversationId).eq('status', 'ended').gt('duration_seconds', 0)
          .order('duration_seconds', { ascending: false }).limit(1).maybeSingle(),
        supabase.from('curry_chat_memory').select('memory, personality').eq('conversation_id', conversationId).maybeSingle(),
      ])
      if (cancelled) return
      setData({
        firstChatted: firstMsgRes.data?.created_at || null,
        longestCall: longestCallRes.data || null,
        curryNotes: curryMemRes.data
          ? { ...(curryMemRes.data.personality || {}), ...(curryMemRes.data.memory || {}) }
          : null,
      })
      setLoading(false)
    }
    load()
    return () => { cancelled = true }
  }, [conversationId])

  return { data, loading }
}

function TimelineView({ conversationId, contactName }) {
  const { data, loading } = useTimelineData(conversationId)

  if (loading) return <div style={s.empty}>Loading timeline…</div>
  if (!data) return <div style={s.empty}>No timeline data yet.</div>

  const notesEntries = data.curryNotes ? Object.entries(data.curryNotes).filter(([, v]) => v && v !== 'true' && v !== 'false') : []

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
      <div style={s.timelineList}>
        {data.firstChatted && (
          <div style={s.timelineRow}>
            <span style={s.timelineIcon}>💬</span>
            <div>
              <div style={s.timelineLabel}>First chatted</div>
              <div style={s.timelineValue}>{new Date(data.firstChatted).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</div>
            </div>
          </div>
        )}
        {data.longestCall && (
          <div style={s.timelineRow}>
            <span style={s.timelineIcon}>{data.longestCall.call_type === 'video' ? '📹' : '📞'}</span>
            <div>
              <div style={s.timelineLabel}>Longest call</div>
              <div style={s.timelineValue}>{formatCallDuration(data.longestCall.duration_seconds)}</div>
            </div>
          </div>
        )}
        {!data.firstChatted && !data.longestCall && (
          <div style={s.empty}>Not enough history with {contactName} yet.</div>
        )}
      </div>

      {notesEntries.length > 0 && (
        <div style={s.notesCard}>
          <div style={s.notesTitle}>✨ What Curry has noticed</div>
          {notesEntries.map(([key, value]) => (
            <div key={key} style={s.notesRow}>
              <span style={s.notesKey}>{prettifyKey(key)}</span>
              <span style={s.notesValue}>{renderValue(value)}</span>
            </div>
          ))}
          <div style={s.footnote}>Learned from Curry conversations in this chat — nothing here was guessed up front.</div>
        </div>
      )}
    </div>
  )
}

// ── Mood Radar (Phase 3) ─────────────────────────────────────────
// Unlike Score/Timeline, this one genuinely is AI-derived — it reads
// recent messages live via Gemini each time it's opened or refreshed.
// It's cached per-conversation in component state only (not persisted),
// so switching tabs back and forth doesn't re-spend a call, but
// reopening the chat later will.
function useMoodRadar(conversationId, session, active) {
  const [radar, setRadar] = useState(null)
  const [otherName, setOtherName] = useState('')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [fetchedFor, setFetchedFor] = useState(null)

  const fetchRadar = useCallback(async () => {
    if (!conversationId || !session) return
    setLoading(true)
    setError('')
    try {
      const data = await callCurryAI('mood_radar', { conversationId }, session)
      if (data.ok) {
        setRadar(data.radar)
        setOtherName(data.otherName || '')
        setFetchedFor(conversationId)
      } else {
        setError(data.error || 'Could not read mood right now')
      }
    } catch (e) {
      setError('Network error reading mood')
    }
    setLoading(false)
  }, [conversationId, session])

  useEffect(() => {
    if (active && conversationId && fetchedFor !== conversationId) fetchRadar()
  }, [active, conversationId, fetchedFor, fetchRadar])

  return { radar, otherName, loading, error, refresh: fetchRadar }
}

function MoodView({ conversationId, session, contactName, active }) {
  const { radar, otherName, loading, error, refresh } = useMoodRadar(conversationId, session, active)

  if (loading && !radar) return <div style={s.empty}>Reading the room…</div>

  if (error) {
    return (
      <div style={s.empty}>
        {error}{' '}
        <button style={s.retryBtn} onClick={refresh}>Try again</button>
      </div>
    )
  }

  if (!radar) return <div style={s.empty}>Not enough recent messages with {contactName} to read mood yet.</div>

  const displayName = otherName || contactName

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
      <div style={s.moodGrid}>
        <div style={s.moodCard}>
          <div style={s.moodEmoji}>{MOOD_EMOJI[radar.myMood] || '🙂'}</div>
          <div style={s.moodWho}>You</div>
          <div style={s.moodTag}>{radar.myMood}</div>
        </div>
        <div style={s.moodCard}>
          <div style={s.moodEmoji}>{MOOD_EMOJI[radar.theirMood] || '🙂'}</div>
          <div style={s.moodWho}>{displayName}</div>
          <div style={s.moodTag}>{radar.theirMood}</div>
        </div>
      </div>

      {radar.summary && (
        <div style={s.notesCard}>
          <div style={s.notesTitle}>How it's reading</div>
          <div style={s.moodSummary}>{radar.summary}</div>
        </div>
      )}

      {radar.recommendation && (
        <div style={s.notesCard}>
          <div style={s.notesTitle}>💡 Curry's take</div>
          <div style={s.moodSummary}>{radar.recommendation}</div>
        </div>
      )}

      <button style={s.refreshBtn} onClick={refresh} disabled={loading}>
        {loading ? 'Refreshing…' : '↻ Refresh'}
      </button>
      <div style={s.footnote}>Read live from recent messages in this chat — this tab uses AI, unlike Score and Timeline.</div>
    </div>
  )
}

// ── Personality Profile (Phase 4) ─────────────────────────────────
// Mostly deterministic — active hour, message style, voice-note usage
// all come straight from real timestamps/message_type on the server.
// Topics/traits are the only AI-read part, and only from the other
// person's actual message content. Same live-per-open, state-cached
// pattern as Mood Radar above (not persisted, re-fetched on reopen).
function usePersonalityProfile(conversationId, session, active) {
  const [profile, setProfile] = useState(null)
  const [otherName, setOtherName] = useState('')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [fetchedFor, setFetchedFor] = useState(null)

  const fetchProfile = useCallback(async () => {
    if (!conversationId || !session) return
    setLoading(true)
    setError('')
    try {
      const data = await callCurryAI('personality_profile', { conversationId }, session)
      if (data.ok) {
        setProfile(data.profile)
        setOtherName(data.otherName || '')
        setFetchedFor(conversationId)
      } else {
        setError(data.error || 'Could not build a profile right now')
      }
    } catch (e) {
      setError('Network error building profile')
    }
    setLoading(false)
  }, [conversationId, session])

  useEffect(() => {
    if (active && conversationId && fetchedFor !== conversationId) fetchProfile()
  }, [active, conversationId, fetchedFor, fetchProfile])

  return { profile, otherName, loading, error, refresh: fetchProfile }
}

function PersonalityView({ conversationId, session, contactName, active }) {
  const { profile, otherName, loading, error, refresh } = usePersonalityProfile(conversationId, session, active)

  if (loading && !profile) return <div style={s.empty}>Getting to know {contactName}…</div>

  if (error) {
    return (
      <div style={s.empty}>
        {error}{' '}
        <button style={s.retryBtn} onClick={refresh}>Try again</button>
      </div>
    )
  }

  if (!profile) return <div style={s.empty}>Not enough messages with {contactName} yet to build a profile.</div>

  const displayName = otherName || contactName

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
      <div style={s.grid}>
        <div style={s.card}>
          <div style={s.cardLabel}>Usually active</div>
          <div style={s.cardValue}>{profile.activeHour}</div>
        </div>
        <div style={s.card}>
          <div style={s.cardLabel}>Message style</div>
          <div style={s.cardValue}>{profile.messageStyle}</div>
        </div>
        {profile.voiceNotePct > 0 && (
          <div style={s.card}>
            <div style={s.cardLabel}>Voice notes</div>
            <div style={s.cardValue}>{profile.voiceNotePct}%</div>
          </div>
        )}
      </div>

      {profile.topics && profile.topics.length > 0 && (
        <div style={s.notesCard}>
          <div style={s.notesTitle}>💭 Often brings up</div>
          <div style={s.chipRow}>
            {profile.topics.map((t, i) => <span key={i} style={s.topicChip}>{t}</span>)}
          </div>
        </div>
      )}

      {profile.traits && profile.traits.length > 0 && (
        <div style={s.notesCard}>
          <div style={s.notesTitle}>✨ {displayName}'s style</div>
          {profile.traits.map((t, i) => (
            <div key={i} style={s.moodSummary}>{t}</div>
          ))}
        </div>
      )}

      <button style={s.refreshBtn} onClick={refresh} disabled={loading}>
        {loading ? 'Refreshing…' : '↻ Refresh'}
      </button>
      <div style={s.footnote}>Active hour, message style, and voice-note usage are computed directly from real messages. Topics and traits are Curry's read of {displayName}'s own words — nothing invented.</div>
    </div>
  )
}

export default function RelationshipInsights({ messages, currentUserId, contactName, conversationId, session, onClose }) {
  const [tab, setTab] = useState('score')
  const insights = useMemo(() => computeInsights(messages, currentUserId), [messages, currentUserId])

  const titleByTab = {
    score: `📊 Insights with ${contactName}`,
    timeline: `🕰️ Timeline with ${contactName}`,
    mood: `🌡️ Mood with ${contactName}`,
    profile: `🧬 Profile of ${contactName}`,
  }

  return (
    <div style={s.panel}>
      <div style={s.header}>
        <span style={s.title}>{titleByTab[tab]}</span>
        <button style={s.closeBtn} onClick={onClose}>✕</button>
      </div>

      <div style={s.tabRow}>
        <button style={tab === 'score' ? s.tabActive : s.tab} onClick={() => setTab('score')}>Score</button>
        <button style={tab === 'timeline' ? s.tabActive : s.tab} onClick={() => setTab('timeline')}>Timeline</button>
        <button style={tab === 'mood' ? s.tabActive : s.tab} onClick={() => setTab('mood')}>Mood</button>
        <button style={tab === 'profile' ? s.tabActive : s.tab} onClick={() => setTab('profile')}>Profile</button>
      </div>

      {tab === 'timeline' ? (
        <TimelineView conversationId={conversationId} contactName={contactName} />
      ) : tab === 'mood' ? (
        <MoodView conversationId={conversationId} session={session} contactName={contactName} active={tab === 'mood'} />
      ) : tab === 'profile' ? (
        <PersonalityView conversationId={conversationId} session={session} contactName={contactName} active={tab === 'profile'} />
      ) : !insights ? (
        <div style={s.empty}>Not enough messages yet to show insights.</div>
      ) : (
        <>
          <div style={s.scoreCard}>
            <div style={s.scoreLeft}>
              <div style={s.scoreEmoji}>{insights.scoreEmoji}</div>
              <div>
                <div style={s.scoreLabel}>{insights.scoreLabelText}</div>
                <div style={s.stars}>{'★'.repeat(insights.stars)}{'☆'.repeat(5 - insights.stars)}</div>
              </div>
            </div>
            <div style={s.scoreNumber}>{insights.score}</div>
          </div>

          <div style={s.grid}>
            <div style={s.card}>
              <div style={s.cardLabel}>Most active</div>
              <div style={s.cardValue}>{insights.mostActiveDay}s</div>
            </div>
            <div style={s.card}>
              <div style={s.cardLabel}>Usually chat in the</div>
              <div style={s.cardValue}>{insights.topBucket}</div>
            </div>
            {insights.replyRate !== null && (
              <div style={s.card}>
                <div style={s.cardLabel}>Reply rate</div>
                <div style={s.cardValue}>{insights.replyRate}%</div>
              </div>
            )}
            {insights.avgResponseLabel && (
              <div style={s.card}>
                <div style={s.cardLabel}>Avg. response</div>
                <div style={s.cardValue}>{insights.avgResponseLabel}</div>
              </div>
            )}
          </div>

          <div style={s.footnote}>
            Score is computed from reply rate, response speed, and message volume in the last {insights.sampleSize} messages — no AI, no guessing.
          </div>
        </>
      )}
    </div>
  )
}

const s = {
  panel: {
    background: 'rgba(30,30,46,0.98)', borderTop: '1px solid rgba(102,126,234,0.3)',
    padding: '14px 16px', display: 'flex', flexDirection: 'column', gap: 12,
  },
  header: { display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  title: { fontSize: 13, fontWeight: 700, color: '#fff' },
  closeBtn: { background: 'none', border: 'none', color: '#666', fontSize: 13, cursor: 'pointer' },
  empty: { fontSize: 13, color: '#9ca3af', padding: '8px 0' },
  tabRow: { display: 'flex', gap: 6, marginBottom: 2 },
  tab: {
    flex: 1, background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.08)',
    borderRadius: 10, color: '#9ca3af', fontSize: 12, fontWeight: 700, padding: '7px 0', cursor: 'pointer',
  },
  tabActive: {
    flex: 1, background: 'rgba(167,139,250,0.18)', border: '1px solid rgba(167,139,250,0.4)',
    borderRadius: 10, color: '#c4b5fd', fontSize: 12, fontWeight: 700, padding: '7px 0', cursor: 'pointer',
  },
  timelineList: { display: 'flex', flexDirection: 'column', gap: 10 },
  timelineRow: { display: 'flex', alignItems: 'center', gap: 10 },
  timelineIcon: { fontSize: 20, width: 30, textAlign: 'center' },
  timelineLabel: { fontSize: 11, color: '#9ca3af', fontWeight: 600 },
  timelineValue: { fontSize: 14, color: '#fff', fontWeight: 700 },
  notesCard: {
    background: 'rgba(167,139,250,0.08)', border: '1px solid rgba(167,139,250,0.25)',
    borderRadius: 12, padding: '10px 12px', display: 'flex', flexDirection: 'column', gap: 6,
  },
  notesTitle: { fontSize: 12.5, fontWeight: 700, color: '#e9d5ff', marginBottom: 2 },
  notesRow: { display: 'flex', justifyContent: 'space-between', gap: 10, fontSize: 12 },
  notesKey: { color: '#9ca3af', fontWeight: 600, flexShrink: 0 },
  notesValue: { color: '#e5e7eb', textAlign: 'right' },
  moodSummary: { fontSize: 12.5, color: '#d8dae8', lineHeight: 1.5 },
  moodGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 },
  moodCard: {
    background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.08)',
    borderRadius: 12, padding: '12px', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 3,
  },
  moodEmoji: { fontSize: 26 },
  moodWho: { fontSize: 12, fontWeight: 700, color: '#fff' },
  moodTag: { fontSize: 11, color: '#c4b5fd', fontWeight: 600, textTransform: 'capitalize' },
  refreshBtn: {
    background: 'rgba(167,139,250,0.12)', border: '1px solid rgba(167,139,250,0.3)', borderRadius: 10,
    color: '#c4b5fd', fontSize: 12, fontWeight: 700, padding: '8px 0', cursor: 'pointer', fontFamily: 'inherit',
  },
  retryBtn: {
    background: 'none', border: 'none', color: '#c4b5fd', fontSize: 12, fontWeight: 700,
    cursor: 'pointer', textDecoration: 'underline', fontFamily: 'inherit', padding: 0,
  },
  scoreCard: {
    display: 'flex', alignItems: 'center', justifyContent: 'space-between',
    background: 'linear-gradient(135deg, rgba(167,139,250,0.16), rgba(240,147,251,0.08))',
    border: '1px solid rgba(167,139,250,0.3)', borderRadius: 14, padding: '12px 16px',
  },
  scoreLeft: { display: 'flex', alignItems: 'center', gap: 10 },
  scoreEmoji: { fontSize: 26 },
  scoreLabel: { fontSize: 14, fontWeight: 700, color: '#fff' },
  stars: { fontSize: 12, color: '#e9d5ff', letterSpacing: 1, marginTop: 2 },
  scoreNumber: { fontSize: 24, fontWeight: 800, color: '#c4b5fd' },
  grid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 },
  card: {
    background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.08)',
    borderRadius: 12, padding: '10px 12px',
  },
  cardLabel: { fontSize: 11, color: '#9ca3af', fontWeight: 600, marginBottom: 3 },
  cardValue: { fontSize: 17, color: '#c4b5fd', fontWeight: 700, textTransform: 'capitalize' },
  chipRow: { display: 'flex', flexWrap: 'wrap', gap: 6 },
  topicChip: {
    background: 'rgba(255,255,255,0.06)', border: '1px solid rgba(167,139,250,0.25)',
    borderRadius: 20, color: '#e9d5ff', fontSize: 11.5, fontWeight: 600, padding: '4px 10px',
  },
  footnote: { fontSize: 10.5, color: 'rgba(255,255,255,0.3)', textAlign: 'center' },
}
